development:
  adapter: postgresql
  host: localhost
  database: westcornwallevents_development
  password: password
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: westcornwallevents_production
  username: rails
  password: <%= ENV['WESTCORNWALLEVENTS_DATABASE_PASSWORD'] %>
